backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "about"
    label: "About Me"
    files:
      - label: "About Me"
        name: "about"
        file: "about.md"
        fields:
          - { label: "Content", name: "body", widget: "markdown" }
